### ISSUE TITLE
I'd like to add I2P support, use catbox as an embedded IRC server/package, and make LIST behavior configurable. Should I upstream or should I fork?

### ISSUE THREAD

**Issue by eyedeekay** [horgh/catbox#1]
I'm interested in making it very easy for small organizations to set up reasonably resilient chat networks inside of I2P(we're a peer-to-peer anonymizing network in case you're not familiar, https://geti2p.net is our homepage) by setting up IRC servers and linking them together, server-to-server, using I2P hostnames instead of normal hostnames.

One effect of catbox's understandable design was that it was very simple for me to discern how to make it easy to configure catbox to set up it's own I2P connections for both from IRC clients and Server-to-Server links automatically using I2P Addresshelper links to configure human-readable hostnames, and the Simple Anonymous Messaging API to set up listeners and dial connections. I have a branch over here where I have added support: https://github.com/eyedeekay/catbox/tree/i2p already.

In that branch, I have also moved main to cmd/catbox/catbox.go and turned the code in the root of the repo into a package, `package catbox` in order to make it possible to treat catbox as a package from another application. I want this so that I can build a bridge between catbox and Java with the JNI and tie the lifetime of the catbox to the lifetime of an I2P router using an I2P Plugin. This would require being able to build catbox as an importable package.

I'd also make the behavior of the LIST command configurable, with the default remaining to not list rooms. I have not added this capability in a branch yet, I wanted to see how hard it would be to port it to I2P first.

However, your README indicates that you don't want to complicate things and I wonder if I'm beginning to push the limits of what you want to do with catbox. Is my use case too odd or obscure for your vision? If so, my intention is to(respectfully) fork and credit you for the original work, it's really just extraordinarily well suited to the I have in mind.

**Comment by horgh** [comment]
That sounds really cool! I actually used to play with I2P years ago but haven't in a while.

It kinda sounds like a fork would be a better option to me. I'm not likely to have a lot of time to work on this unfortunately. Thank you for reaching out & the info though, it sounds neat! :-)

**Comment by eyedeekay** [comment]
Thanks for getting back to me, my fork is over here: https://i2pgit.org/idk/terrarium if you're ever curious :)
