### ISSUE TITLE
Use of closed connection after QUIT

### ISSUE THREAD

**Issue by ghost** [horgh/catbox#2]
After client closed connection i see this... warning?
```
2023/10/21 15:11:34 Client 0 127.0.0.1:40376: Read problem: error reading: read tcp 127.0.0.1:6667->127.0.0.1:40376: use of closed network connection
2023/10/21 15:11:34 Client 0 127.0.0.1:40376: Reader shutting down.
2023/10/21 15:11:34 Client 0 127.0.0.1:40376: Writer shutting down.
```

**Comment by horgh** [comment]
Yeah, it's just overly verbose logging. There's nothing wrong, it just detected the client is gone.

**Comment by ghost** [comment]
> Yeah, it's just overly verbose logging. There's nothing wrong, it just detected the client is gone.

> Read problem: error reading: read tcp 127.0.0.1:6667->127.0.0.1:40376: use of closed network connection

Looks like error

**Comment by horgh** [comment]
It's technically an error yeah :). But nothing is wrong. It doesn't need to be logged really.
